#!/usr/bin/env bash
#install HAproxy and init server as loadbalancer
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
sudo cat >> /etc/haproxy/haproxy.cfg<<EOF

frontend haproxynode
 bind *:80
 mode http
 default_backend backendnodes

backend backendnodes
 balance roundrobin
 server 13187-web-01 3.237.35.220:80 check
 server 13187-web-02 3.230.143.190:80 check

EOF

sudo service haproxy restart
